// Default keywords that users can extend
export const DEFAULT_WORK_KEYWORDS = [
  "meeting",
  "completed",
  "done",
  "finished",
  "task",
  "project",
  "deadline",
  "delivered",
  "implemented",
  "fixed",
  "deployed",
  "tested",
  "reviewed",
  "approved",
  "release",
  "launch",
  "demo",
  "presentation",
  "discussion",
  "planning",
  "development",
  "coding",
  "bug",
  "feature",
  "requirement",
  "specification",
  "design",
  "working",
  "work",
  "progress",
  "update",
  "created",
  "added",
  "building",
  "resolved",
  "issue",
  "api",
  "backend",
  "frontend",
  "database",
  "server",
  "mobile",
  "app",
  "component",
  "route",
  "payment",
  "client",
  "contractor",
  "admin",
  "upload",
  "download",
  "testing",
  "apk",
  "build",
  "deploy",
  "push",
  "pull",
  "commit",
  "branch",
  "merge",
  "repository",
  "github",
  "aws",
  "cloud",
  "notification",
  "socket",
  "real-time",
  "tracking",
  "location",
  "gps",
  "map",
  "google",
  "firebase",
  "react",
  "node",
  "javascript",
];

export const DEFAULT_MEETING_KEYWORDS = [
  "meeting",
  "call",
  "zoom",
  "teams",
  "conference",
  "discussion",
  "standup",
  "scrum",
  "review",
  "planning",
  "demo",
  "presentation",
  "join",
  "link",
  "invite",
  "google meet",
  "meet.google.com",
];

// WhatsApp message patterns
export const WHATSAPP_PATTERNS = [
  // M/D/YY, H:MM AM/PM - Contact Name: Message
  /(\d{1,2}\/\d{1,2}\/\d{2,4}),\s*(\d{1,2}:\d{2}\s*[AP]M)\s*-\s*([^:]+):\s*(.+)/,
  // DD/MM/YYYY, HH:MM - Contact Name: Message
  /(\d{1,2}\/\d{1,2}\/\d{2,4}),\s*(\d{1,2}:\d{2})\s*-\s*([^:]+):\s*(.+)/,
  // [DD/MM/YYYY, HH:MM:SS] Contact Name: Message
  /\[(\d{1,2}\/\d{1,2}\/\d{2,4}),\s*(\d{1,2}:\d{2}:\d{2})\]\s*([^:]+):\s*(.+)/,
];

// Activity categories
export const ACTIVITY_CATEGORIES = {
  MEETING: "Meeting",
  TASK_COMPLETED: "Task Completed",
  BUG_ISSUE: "Bug/Issue",
  DEVELOPMENT: "Development",
  REVIEW_TESTING: "Review/Testing",
  DEPLOYMENT: "Deployment",
  PLANNING: "Planning",
  GENERAL: "General",
};

// Priority levels
export const PRIORITY_LEVELS = {
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
};
